# Generated by Django 2.2 on 2020-12-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'demo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zakernews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pubdate', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('detail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_mpic', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_counts', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'zakernews',
                'managed': False,
            },
        ),
    ]
