# Generated by Django 2.2 on 2020-12-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0003_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='icon',
            field=models.ImageField(upload_to='%Y%m/icons'),
        ),
    ]
